name: Build AList Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Project Structure
      run: |
        mkdir -p app/src/main/java/com/example/alistapp
        mkdir -p app/src/main/res/layout
        mkdir -p app/src/main/res/mipmap-hdpi
        mkdir -p app/src/main/res/mipmap-mdpi
        mkdir -p app/src/main/res/mipmap-xhdpi
        mkdir -p app/src/main/res/mipmap-xxhdpi
        mkdir -p app/src/main/res/mipmap-xxxhdpi
        mkdir -p .github/workflows

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 创建修改后的 settings.gradle
    - name: Create settings.gradle
      run: |
        cat > settings.gradle << 'EOL'
        pluginManagement {
            repositories {
                google()
                mavenCentral()
                gradlePluginPortal()
            }
            plugins {
                id 'com.android.application' version '8.1.0'
                id 'org.jetbrains.kotlin.android' version '1.8.0'
            }
        }

        dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
            repositories {
                google()
                mavenCentral()
            }
        }

        rootProject.name = "AList App"
        include ':app'
        EOL

        # 添加 gradle.properties 文件以支持 AndroidX
        echo "android.useAndroidX=true" >> gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties

    # 创建简化后的 build.gradle
    - name: Create build.gradle
      run: |
        cat > build.gradle << 'EOL'
        // Top-level build file
        EOL

    - name: Create app/build.gradle
      run: |
        cat > app/build.gradle << 'EOL'
        plugins {
            id 'com.android.application'
            id 'org.jetbrains.kotlin.android'
        }
        
        android {
            namespace "com.example.alistapp"
            compileSdk 34
            
            defaultConfig {
                applicationId "com.example.alistapp"
                minSdk 21
                targetSdk 34
                versionCode 1
                versionName "1.0"
            }
            
            buildTypes {
                release {
                    minifyEnabled false
                }
            }
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_17
                targetCompatibility JavaVersion.VERSION_17
            }
            kotlinOptions {
                jvmTarget = "17"
            }
        }
        
        dependencies {
            implementation 'androidx.core:core-ktx:1.12.0'
            implementation 'androidx.appcompat:appcompat:1.6.1'
            implementation 'com.google.android.material:material:1.11.0'
        }
        EOL

    # 下载并初始化 Gradle
    - name: Setup Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-8.2-bin.zip
        unzip gradle-8.2-bin.zip
        ./gradle-8.2/bin/gradle wrapper --gradle-version 8.2
        chmod +x gradlew

    - name: Add Launcher Icons
      run: |
        # 创建一个简单的占位图标
        convert -size 48x48 xc:blue app/src/main/res/mipmap-mdpi/ic_launcher.png
        convert -size 72x72 xc:blue app/src/main/res/mipmap-hdpi/ic_launcher.png
        convert -size 96x96 xc:blue app/src/main/res/mipmap-xhdpi/ic_launcher.png
        convert -size 144x144 xc:blue app/src/main/res/mipmap-xxhdpi/ic_launcher.png
        convert -size 192x192 xc:blue app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

    - name: Create MainActivity
      run: |
        cat > app/src/main/java/com/example/alistapp/MainActivity.kt << 'EOL'
        package com.example.alistapp
        
        import android.content.Context
        import android.os.Bundle
        import android.webkit.WebView
        import android.webkit.WebViewClient
        import android.widget.Button
        import android.widget.EditText
        import androidx.appcompat.app.AppCompatActivity
        
        class MainActivity : AppCompatActivity() {
            private lateinit var webView: WebView
            private lateinit var urlInput: EditText
            private lateinit var saveButton: Button
        
            override fun onCreate(savedInstanceState: Bundle?) {
                super.onCreate(savedInstanceState)
                setContentView(R.layout.activity_main)
        
                webView = findViewById(R.id.webView)
                urlInput = findViewById(R.id.urlInput)
                saveButton = findViewById(R.id.saveButton)
        
                webView.settings.apply {
                    javaScriptEnabled = true
                    domStorageEnabled = true
                    databaseEnabled = true
                    setAppCacheEnabled(true)
                }
                webView.webViewClient = WebViewClient()
        
                val sharedPref = getPreferences(Context.MODE_PRIVATE)
                val savedUrl = sharedPref.getString("alist_url", "")
                if (!savedUrl.isNullOrEmpty()) {
                    urlInput.setText(savedUrl)
                    webView.loadUrl(savedUrl)
                }
        
                saveButton.setOnClickListener {
                    val url = urlInput.text.toString()
                    if (url.isNotEmpty()) {
                        sharedPref.edit().putString("alist_url", url).apply()
                        webView.loadUrl(url)
                    }
                }
            }
        
            override fun onBackPressed() {
                if (webView.canGoBack()) webView.goBack()
                else super.onBackPressed()
            }
        }
        EOL

    - name: Create Layout
      run: |
        cat > app/src/main/res/layout/activity_main.xml << 'EOL'
        <?xml version="1.0" encoding="utf-8"?>
        <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:padding="16dp">
        
            <EditText
                android:id="@+id/urlInput"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="输入AList地址"
                android:inputType="textUri" />
        
            <Button
                android:id="@+id/saveButton"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="保存并加载" />
        
            <WebView
                android:id="@+id/webView"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1" />
        
        </LinearLayout>
        EOL

    - name: Create AndroidManifest
      run: |
        cat > app/src/main/AndroidManifest.xml << 'EOL'
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="com.example.alistapp">
        
            <uses-permission android:name="android.permission.INTERNET" />
        
            <application
                android:allowBackup="true"
                android:icon="@mipmap/ic_launcher"
                android:label="AList App"
                android:supportsRtl="true"
                android:theme="@style/Theme.AppCompat.Light.DarkActionBar"
                android:usesCleartextTraffic="true">
                <activity
                    android:name=".MainActivity"
                    android:exported="true"
                    android:configChanges="orientation|keyboardHidden|screenSize"
                    android:launchMode="singleTask">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOL

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: alist-app
        path: app/build/outputs/apk/debug/app-debug.apk
